antonbabenko/pre-commit-terraform

terraform_docs.sh

On Linux, the `md5` command is called `md5sum`.
Instead of creating our own tempfile name, use `mktemp` which is available on both BSD and Linux.

Fixes use of md5 for tempfile name

---

terraform_docs.sh

This replaces the sed commands which required GNU sed be installed with
perl versions. This should make this script more universally usable
(e.g., on macOS) without installing additional tools.
Closes #14.

Replace terraform_docs use of GNU sed with perl

---

terraform_docs.sh

This pull request uses [agriffis/pure-getopt](https://github.com/agriffis/pure-getopt), a *GNU getopt* replacement in pure Bash. We use *getopt* to declare and process options `-a` and `--args` to relay arguments to the actual execution of `terraform-docs`. Resolves #23.
Examples:
```
terraform_docs.sh     -a '--with-aggregate-type-defaults' main.tf outputs.tf variables.tf
terraform_docs.sh --args='--with-aggregate-type-defaults' main.tf outputs.tf variables.tf
```
@antonbabenko the `getopts` function has been inlined to allow for better portability of `terraform_docs.sh`, but could be externalized and sourced into the script if this is what you prefer.

Add feature to pass options to terraform-docs.

---

.pre-commit-hooks.yaml

It turns out that `pre-commit` defaults to running hooks in parallel. This means it will take a batch of files, break them into chunks, and run those together.  The `terraform_docs.sh` script strips the filenames and runs over a set of unique paths.  That means that parallel operations can be running int he same directories. To avoid pre-commit doing parallel operations on similar file paths I've added `require_serial: true` to the hook descriptions.
For some detail, I ran into this while running on docker.  I copied a large terraform directory into a docker container and then ran the `terraform-docs` pre-commit hook to mimic our CI environment in CircleCI.  In about 10-20% of cases the hook would fail and the result would be that one or more files were deleted.  It turns out the chunking …

Require terraform-docs runs in serial

---

terraform_validate_with_variables.sh

Exit code for failed 'terraform validate -check-variables=true', so it fails pre-commit check correctly.
[https://github.com/antonbabenko/pre-commit-terraform/issues/22](https://github.com/antonbabenko/pre-commit-terraform/issues/22)

Add exit code for 'terraform validate' so pre-commit check fails

---

terraform_validate_with_variables.sh

`-n` checks to see if a variable is defined.  The way the script is currently written, the `terraform_validate_with_variables` check will always fail because the last thing it does is check to see if `error` is defined and does an `exit 1` if so.  This change makes it so that we check to see `error` is not `0` instead.

fix check for errors at the end on validate w/ variables

---

README.md
terraform_docs.sh

This solution is based on great work by @osterman and @cytopia :

Added support for terraform_docs for Terraform 0.12

---

.pre-commit-hooks.yaml
README.md
terragrunt_fmt.sh

Provides a `terragrunt_fmt` hook for users of Terragrunt.
Terragrunt has its own formatter for the `.hcl` files that are used throughout a Terragrunt-enabled repository. These files are not formatted by Terraform, and therefore, Terragrunt needs its own formatting hook.
I wanted to also be able to format my Terragrunt configurations.
Ran the following command against a Terragrunt repo using a local copy of this branch:
```shell
$ pre-commit try-repo \
--verbose \
--all-files \
'/local/copy/of/this/pre-commit-terraform' \
terragrunt_fmt
```
Only downside is it takes a bit of time.

Formatter for Terragrunt HCL files

---

.pre-commit-hooks.yaml
terraform_tflint.sh

Added support for TFLint (https://github.com/wata727/tflint).
This commit addresses #37 
Signed-off-by: Costin Galan <costin.galan@mambu.com>

Added support for TFLint with --deep parameter

---

README.md

Updating the rev in the README.
In order for `terraform_tflint` to work, the rev must be at least `v1.19.0`.

update rev in README.md

---

terraform_docs.sh

This PR fixes a when a key named `description` is inside the `type` block of a variable section:
```hcl
variable "ingress_cidr_blocks" {
description = "Bzzzzz"
type = list(
object({
description = string
cidr_blocks = string
from_port   = number
to_port     = number
protocol    = string
})
)
default = [
{
description = "SG"
cidr_blocks = "10.0.0.0/32"
from_port   = 22
to_port     = 22
protocol    = "tcp"
},
]
}
```
* Refs: https://github.com/antonbabenko/pre-commit-terraform/issues/65
* Refs: https://github.com/antonbabenko/pre-commit-terraform/issues/64
* Refs: https://github.com/cytopia/docker-terraform-docs/pull/23
Test for this can be found here: https://github.com/cytopia/docker-terraform-docs/blob/master/tests/0.12/main.tf#L60
I tried to fix this to the best of my knowledge and …

Fixes #65: terraform-docs should not fail if complex types contain 'description' keyword

---

CHANGELOG.md
README.md
terraform_tflint.sh

This changes the behaviour of the TFlint hook from enforcing `--deep` to allowing arbitrary args to be specified (including, but not limited to, `--deep`) in the hook configuration.
Addresses #71 and a few comments in #53.
I'm in a similar boat to the other commenters - using this hook for non-AWS Terraform code, in my case to enforce some terraform rules rather than AWS rules (commented variables, commented outputs, pinned versions etc).

Allow arbitrary TFlint args (instead of --deep by default)

---

terraform_docs.sh

With the actual behavior of the `terraform_docs.sh` script, we can't pass command options. We can only pass global options like `--with-aggregate-type-defaults`, `--no-sort`, etc. By moving args after `markdown` command, we can pass global and commands options at once.
~## terraform-docs without escape hook~
~I don't since which version of terraform-docs, but it try to escape all values with underscore. Everything is  discussed in the following issue https://github.com/segmentio/terraform-docs/issues/111 and PR https://github.com/segmentio/terraform-docs/pull/117.~
So with this PR I add the `--no-escape` option to resolve doc generation issue https://github.com/terraform-aws-modules/terraform-aws-eks/pull/668
~_**I can remove this hook if you think we don't need to defined it here**_~

Move terraform-docs args after md command

---

terraform_tflint.sh

It will avoid this bug:
```
/Users/robinho/.cache/pre-commit/repoxfm3uiv2/terraform_tflint.sh: line 42: pushd: modules/prometheus/lb.tf modules/prometheus/ec2.tf modules/prometheus/variables.tf modules/prometheus: No such file or directory
```

tflint: iterate over files

---

terraform_docs.sh

Without this fix `terraform_docs` hook was always exiting with code 1 when using Terraform 0.11:
```
Terraform docs...........................................................Failed
- hook id: terraform_docs
- duration: 0.55s
- exit code: 1
```

Fixed exit code for terraform 0.11 branch in terraform_docs

---

terraform_docs.sh

The `args` variable was mistakenly double-quoted in one of the recent commits, which made it impossible to pass multiple arguments to `terraform-docs`.
With this change it is possible to configure the hook like this:
```yaml
hooks:
args:
- '--args=document --indent 3'
```

fix: Allow passing multiple args to terraform-docs

---

.pre-commit-hooks.yaml
terraform_validate.sh

This is a fix toward allowing the `terraform_validate` hook to correctly process a repository that has Terraform files in subdirectories per #59 and #87. This is achieved by working down a path to search for a `.terraform` subdirectory that indicates that a `terraform init` has been run in that directory. It then `cd`s to that path, runs `terraform validate` against the new path (taking account the `cd`), and `cd`s back to the original directory.
I ran `pre-commit run --all-files` using my fork locally in the following repos from my org to test:
https://github.com/cisagov/skeleton-tf-module/tree/improvements/upstream_updates
https://github.com/cisagov/cyhy_amis
I also pushed the change to the first repo to ensure our GitHub Actions tasks ran successfully. You can see testing from the …

fix: Change terraform_validate hook functionality for subdirectories with terraform files

---

.pre-commit-hooks.yaml
README.md
terraform_tfsec.sh

Add an integration for TFSec: https://github.com/liamg/tfsec

feat: Support for TFSec

---

README.md

Since the change to make terraform_validate recursive on April 4th, coreutils is required on macOS because there is no `realpath` available by default

docs: Added coreutils as requirements in README.md

---

.pre-commit-hooks.yaml
README.md
terragrunt_validate.sh

Simple hook to execute terragrunt validate
Suggest having the `disable_init` in the [remote_state block](https://terragrunt.gruntwork.io/docs/reference/config-blocks-and-attributes/#remote_state) to avoid having to init backend for terragrunt validate.
```hcl
remote_state {
backend      = "gcs"
disable_init = tobool(get_env("TERRAGRUNT_DISABLE_INIT", "false"))
config = {
bucket = "terraform-states"
prefix = "terragrunt/${path_relative_to_include()}"
}
}
```

feat: add terragrunt validate hook

---

README.md
lib_getopt
terraform_tflint.sh
terraform_validate.sh

Adds support for passing env vars and arguments to terraform_validate
Requires #124.
Fixes #116 and #119 , obsoletes #114 + #118.

fix: Pass args and env vars to terraform validate

---

terraform_docs.sh

Fix a bug in terraform_docs caused by `set -o pipefail`

fix: Fix bug in terraform_docs hook introduced recently

---

.pre-commit-config.yaml
terraform_docs.sh

@antonbabenko A serious regression has been introduced in v1.34.0 in the process of factoring out `getopt`. Starting with that version, `terraform_docs` pre-commit hook would only process one terraform module, ignoring any other modules that are part of the commit.
This PR attempts to fix the regression. I have tested it on Ubuntu Focal (GNU bash, version 5.0.17), but I would appreciate if anyone could also test it on Bash 4.x and on MacOS.
Please note that `args` are still passed around in the script as a single argument (just as it was), and I have also successfully verified the correct operation with multiple `--args=` in the pre-commit YAML configuration (fixed earlier in #98).
Side note: other hooks may also be affected in a similar way, but I haven't tested them because we are not …

fix: Correctly handle arrays in terraform_docs.sh

---

.pre-commit-hooks.yaml

fix: terraform-docs version 0.10 removed with-aggregate-type-defaults

---

terraform_docs.sh

Adds support for terraform_docs running on Git Bash over Windows environment.
It fixs #128

fix: terraform_docs compatible with Git bash on Windows

---

terraform_docs.sh

Got this error using `v1.42.0` on terraform_docs hook:
```sh
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x13fdbe6]
```
Looks like the new `v0.10.0` terraform-docs is going the awk script route instead of "Using terraform-docs 0.8+ (preferred)" route because the regex matches when it shouldn't.

fix: Fix regex considering terraform-docs v0.10.0 old

---

.pre-commit-config.yaml
README.md
terraform_docs.sh
terraform_tfsec.sh
terraform_validate.sh

feat: Make terraform_validate to run init if necessary

---

.pre-commit-config.yaml
README.md
pre_commit_hooks/terraform_docs_replace.py

The --sort-inputs-by-required was removed here: https://github.com/terraform-docs/terraform-docs/commit/b6a6ad1bbf77e99fa920dee784b9936170b35477#diff-2fb3c316208521762f7701f5a16834dc239636c3b6c8ec403d02688e5f7da53eL23 after being marked for deprecation in favor of the --sort-by-required flag instead. and noted for deprecation here: https://github.com/terraform-docs/terraform-docs/releases/tag/v0.8.0
This PR switches to the new supported flag which has been available for 6 months now. 
Caveat: Existing terraform-docs users using 0.9.1 or older will need to upgrade. If relevant messaging is necessary, that can be added.

fix: Correct deprecated parameter to terraform-docs

---

CHANGELOG.md
pre_commit_hooks/terraform_docs_replace.py

Since updating to terraform-docs 0.11.0+ (also affects 0.11.1 and 0.11.2) all my README.md's are now missing the last line!
After a little bit of digging I've noticed that, since version 0.11.0, `terraform-docs` no longer adds an extra empty newline at the end. This PR amends the sed pattern to produce the same output in <0.11.0 as in 0.11.0+:
0.10.0:
```
$ terraform-docs --sort-by-required md ./ | gsed -e '$ d' -e 'N;/^\n$/D;P;D' | tail -n 3
|------|-------------|
| ids | List of IDs of the created instances |
| private\_ips | The private IP addresses assigned to the instances |
$ terraform-docs --sort-by-required md ./ | gsed -e '${/^$/d;}' -e 'N;/^\n$/D;P;D' | tail -n 3
|------|-------------|
| ids | List of IDs of the created instances |
| private\_ips | The private IP addresses …
```

fix: remove sed postprocessing from the terraform_docs_replace hook to fix compatibility with terraform-docs 0.11.0+

---

README.md

- Adds `checkov` to the install section as it was missing. 
- Are you generally interested in having a `Dockerfile` in the repo with the install instruction, so we can verify them in the future?

docs: Added checkov install

---

.dockerignore
Dockerfile
README.md

- adds Dockerfile for `ubuntu` to have easy usage
```sh
docker build -t pre-commit .
docker run -v $(pwd):/lint -w /lint pre-commit run -a 
```
- see discussion in #182. Let me know if it fits in here

chore: add dockerfile 

---

README.md

Command 
```bash
python3.7 -m pip install -U checkovpython3.7 -m pip install -U checkov
```
is probably a typo with one command being pasted twice.

chore: Fix typo on command in readme

---

Dockerfile
README.md

- use curl to obtain `tfsec` and use `latest` version as well and hence remove go as I got an error at
```sh
env GO111MODULE=on go get -u github.com/tfsec/tfsec/cmd/tfsec@${TFSEC_VERSION}
```
- use latest terraform version `0.15.0` by default
- reduce the docker image size by ~50%

fix: Fix and pin versions in Dockerfile

---

.pre-commit-config.yaml
Dockerfile
README.md

feat: Add mixed line ending check to prevent possible errors

---

.github/workflows/stale-actions.yaml

Fix Warning founded afrer [GH action run](https://github.com/antonbabenko/pre-commit-terraform/runs/3577117856?check_suite_focus=true) by removing unsupported parameter.
Check next run after change merge.
Also, this action have dry-run options as it described in action readme, but for this little fix it will be overkill.
It just warning, so workaraund is do nothing

fix: GH stale action -  remove unsupported setting

---

.pre-commit-hooks.yaml

The recent versions of `terraform-docs` extract provider version from terraform lock files. Starting from version 0.15.0, this behaviour can also be controlled by `--lockfile` command line flag. Since the new behaviour is active by default, add lock files to the pattern that triggers pre-commit hook, so that README files are updated on any changes in lock files.
Tested locally by overriding file pattern in `.pre-commit-config.yaml` inside the client project.

fix: trigger terraform-docs on changes in lock files

---

README.md

docs: Describe hooks usage and improve examples

---

terraform_tflint.sh

Close #161, close #162
Here is output preview:
<details><summary>before</summary>
```bash
✘130 ➜ pre-commit run -a terraform_tflint
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 2
WARNING: The plugin `aws` is not explicitly enabled. The bundled plugin will be enabled instead, but it is deprecated and will be removed in a future version. Please see https://github.com/terraform-linters/tflint/pull/1160 for details.
WARNING: The plugin `aws` is not explicitly enabled. The bundled plugin will be enabled instead, but it is deprecated and will be removed in a future version. Please see https://github.com/terraform-linters/tflint/pull/1160 for details.
WARNING: The plugin `aws` is …
```

feat: Add PATH outputs when TFLint found any problem

---

.editorconfig
.github/CONTRIBUTING.md
.gitignore
README.md
tests/Dockerfile
tests/hooks_performance_test.sh

Add performance tests to simplify provide feedback about changes and find possible issues.
Relates #219, #159, #216
See appropriate README.md section

docs: Add contributing guide and docs about performance tests

---

README.md

docs: Document terraform_tfsec args usage

---

Dockerfile

Decreased image size and build time:
| All hooks  | Ubuntu | Alpine | Decreased by |
| ---------- | ------ | ------ | ------------ |
| Build time | 2m 50s | 1m 47s | 63s, 37%     |
| Image size | 625MB  | 568MB  | 67MB, 10%    |
| Without hooks | Ubuntu | Alpine | Decreased by |
| ------------- | ------ | ------ | ------------ |
| Build time    | 1m 45s | 0m 41s | 64s, 61%     |
| Image size    | 259MB  | 164MB  | 85MB, 37%    |
Co-authored-by: Balazs Hamorszky <balihb@gmail.com>
Something was updated in the Docker image based on Debian/Ubuntu and now it does not meet deps.
The quick fix was not found, so I decided to migrate the image to alpine, hopefully, @balihb found all needed deps earlier. 
Fixes #277
Closes #239 as outdated duplicate 
```bash …
```

feat: Updated Docker image from Ubuntu to Alpine

---

README.md
pre_commit_hooks/__init__.py

Relates to https://github.com/antonbabenko/pre-commit-terraform/issues/248#issuecomment-963499190

chore: Add deprecation notice to `terraform_docs_replace`

---

README.md
terraform_docs.sh

As someone who often does not copy commands/args but types them out, I encountered an issue when trying to add the argument `--add-to-existing-file` for `terraform_docs`, as it has a typo in the name currently. This PR updates `exiting` to `existing` in all places.
This, however, is a breaking change for people that are using this argument with its current name. In order to make it non-breaking, we can check for `--add-to-exiting-file|--add-to-existing-file)` in the `case` block maybe?
Tested using this:
```yaml
repos:
- repo: git://github.com/mj3c/pre-commit-terraform
rev: master
hooks:
args:
- --hook-config=--add-to-existing-file=true
```

fix: typo in arg name for terraform-docs

---

.github/workflows/build-image.yaml

A basic workflow for building the image and publishing it to the registry of this project.  Builds on a new release and pushes to `master`.
Fixes #220.
I've built and pushed images to my own fork.

chore: Publish container image on release

---

Dockerfile

Fixes #287
Add missing packages (gcc and musl-dev) at docker builder stage.
Run docker build on macOS and Ubuntu.

fix: Fixed docker build

---

.github/workflows/build-image.yaml
Dockerfile
README.md

- Remove useless
- Fix pre-build docker image
- Document pre-build docker image usage

fix: pre-build docker image

---

terraform_tflint.sh

In a monorepo tflint is currently stopping after analysing the first module. This is because of the `set -e` that causes the script to exit. This change disables it temporarily for executing `tflint`, catches the exit codes from the `tflint` executions and then uses the exit code for the function. It also removes the `pushd`/`popd` since it is not necessary because tflint can just receive the path as an argument.
Create a mono repo with two or more modules in different folders, with code that makes tflint report something. Notice that before this change, it just analyses one of the modules. With this change it will keep analysing the modules and report the output for all of them.

fix: analyse all folders with tflint and don't stop on first execution

---

README.md
terraform_validate.sh

This adds support for passing arguments to `terraform init` via `--init-args`.
My use case is passing `-lockfile=readonly`, I do not want this hook to modify the lock file, I leave that to `terraform_providers_lock`.
It avoids the issue describe in this discussion: https://github.com/renovatebot/renovate/discussions/11821
I have run the pre-commit on a repository. Directory are validated, `init` takes the arguments

feat: Pass custom arguments to terraform init in `terraform_validate` hook

---

terraform_tflint.sh

This has been removed in #289, but it breaks `tflint` for features like the `--modules` flag which require the directory to be initialized. `tflint` looks for the `.terraform` directory in the current working directory.
Run on a repository with `--modules` argument, both in a valid and an invalid state, previous behavior is restored.

fix: Restore current working directory behavior

---

.pre-commit-hooks.yaml

During https://github.com/antonbabenko/pre-commit-terraform/pull/305#pullrequestreview-837797221 found that tag v1.62.1 with `require_serial: true` took 9s when without taking took 20s.
The root cause is same to previous `require_serial: true`  fixes - `pre-commit` run hook multiply times in the same folder/
So, let's not wait to PR merge, and implement this fix now.

fix: Speedup `terrascan` hook up to x3 times in big repos

---

infracost_breakdown.sh
terraform_docs.sh
terraform_fmt.sh
terraform_providers_lock.sh
terraform_tflint.sh
terraform_tfsec.sh
terraform_validate.sh
terragrunt_fmt.sh
terragrunt_validate.sh
terrascan.sh

Make hooks the as same as possible 
The next big thing will be to move the `common::` functions to separate file, and import them to all hooks.
Then, most of the hooks will look like this:
```bash
#!/usr/bin/env bash
. common.sh
function main {
common::initialize
common::parse_cmdline "$@"
common::per_dir_hook "${ARGS[*]}" "${FILES[@]}"
}
function per_dir_hook_unique_part {
local -r args="$1"
local -r dir_path="$2"
terrascan scan -i terraform ${args[@]}
local exit_code=$?
return $exit_code
}
[[ ${BASH_SOURCE[0]} != "$0" ]] || main "$@"
```
```yaml
repos:
rev: a243f3f314de907b5c964d7adcb9e9fa128b7ac9
hooks:
```
---
Merge will affect:
* …

chore: Refactor all hooks

---

.github/CONTRIBUTING.md
.github/workflows/release.yml
tests/hooks_performance_test.sh

That needed to guarantee that no data from previous checks included

chore: Cleanup file with test data

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml
infracost_breakdown.sh
terraform_docs.sh
tests/hooks_performance_test.sh

chore: Add shellcheck and make checks passing

---

hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh

Let's move forward and use the code style provided by Google as the main.
* [Google style guide for BASH](https://google.github.io/styleguide/shellguide.html)

chore: Document functions (based on google style guide)

---

.github/CONTRIBUTING.md
.github/workflows/pre-commit.yaml
.pre-commit-config.yaml
Dockerfile
hooks/infracost_breakdown.sh
tests/Dockerfile

This PR is partly a subset of #319 originally made by @balihb, partly inspired by #319 PR.
It includes:
* [`hadolint`](https://github.com/hadolint/hadolint) check for Dockerfiles
* Fix Dockefiles issues
* Fix `infracost_breakdown` shellcheck issue. (other introduced fix not works)
* Fix performance test docker image, forgotten during refactoring a few months ago.
```yaml
repos:
rev: 7e34de024972344787a1704e5952f812148aa33b
hooks:
- id: infracost_breakdown
args:
- --args=--path=./environment/qa
- --hook-config='.totalHourlyCost >= 0.1'
- --hook-config=".totalHourlyCost|tonumber > 1"
- -h ".projects[].diff.totalMonthlyCost|tonumber!=10000"
- -h [.projects[].diff.totalMonthlyCost | select …
```

chore: Add hadolint check for Dockerfiles

---

README.md

As noted in the change, there is a bug affecting terraform validate
when used with a module that also requires multiple aliased providers.
There is little activity on this bug, leave it an open question on if
or when it will be fixed. This documents a couple of workaround options
in the interim.
Fixes #330 
Define a module with configuration aliases as described in #330, and run terraform validate.  This should error out.
Following the instructions provided in the documentation update prevents the error and offers workarounds other than disabling the terraform_valdiate hook.

docs: Add workaround for configuration_aliases tf bug

---

hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh

Close #309 
```bash
time pre-commit try-repo --ref 44ae15a https://github.com/carlosbustillordguez/pre-commit-terraform.git terrascan -a
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/carlosbustillordguez/pre-commit-terraform.git
rev: 44ae15a
hooks:
-   id: terrascan
===============================================================================
```

feat: Improve performance during `pre-commit --all (-a)` run

---

hooks/terraform_tfsec.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh

…m_tfsec`, `terragrunt_fmt` and `terragrunt_validate`
Speedup hooks execution on `pre-commit run --all`
Closes #309
```yaml
repos:
rev: 7ebbe57df62dce6d50cfe11a12566850d96a9613
hooks:
- id: terraform_tfsec
#args:
- id: terragrunt_fmt
- id: terragrunt_validate
```

feat: Improved speed of `pre-commit run -a` for multiple hooks

---

.github/workflows/build-image-test.yaml
hooks/_common.sh

Invalid workflow file: .github/workflows/build-image-test.yaml#L22
The workflow is not valid. .github/workflows/build-image-test.yaml (Line: 22, Col: 13): Unexpected symbol: '"true"'. Located at position 53 within expression: steps.changed-files-specific.outputs.any_changed == "true"

chore: Fix docker test workflow

---

hooks/_common.sh

In new versions, macOS use `zsh` by default and include bash 3.2 for compatibility reasons.
That OS will never upgrade bash to 4+, during license issues.
[theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features](https://www.theverge.com/2019/6/4/18651872/apple-macos-catalina-zsh-bash-shell-replacement-features)
So looks like we need to maintain compatibility with bash 3.2 🙄
**Or require bash 4.2+ as deps.**
Fixes #337
Run on macOS:
```yaml
repos:
rev: 48bc03ca3f0f2f782d2f430069868019a6892062
hooks:
- id: terraform_fmt
```

fix: Make hooks bash 3.2 compatible

---

hooks/terraform_tflint.sh

- [x ] This PR enhances existing functionality.
Just a quick `tflint --init` before running tflint to ensure plugins are installed.

feat: Adding init to terraform_tflint hook

---

.github/PULL_REQUEST_TEMPLATE.md

All PR's that have #123 in their description, that are added by the PR template, force release action to generate comments in #123 issue.

chore: Avoid mention issue 123 during releases

---

README.md
hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_checkov.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

Fixes #336, #349 and #367
Run any hook on MacOs w/o `coreutils`
```yaml
repos:
rev: 307f48dae422203f31fa888f6cad7d12014ad260
hooks:
```

feat: Removed `coreutils` (realpath) from dependencies for MacOS

---

README.md
hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_checkov.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

`*` - All hooks, except deprecated.
Implement a use case from #347, but without affecting UX.
Use case:
>Context: I need to pass in the location of an alternate tflint config in CI.
The location is based on an environment variable in my CI environment, so
hard-coding the value as an argument isn't tenable.
Close #347
1. Export env vars, eg `export CONFIG_NAME=.tflint; export CONFIG_EXT=hcl`
2. Add env vars to your .pre-commit-config.yaml`
```yaml
repos:
rev: 182254e43fdfa6ff79f849cbaeb150d9c593a383
hooks:
- id: terraform_tflint
args:
- --args=--config=__GIT_WORKING_DIR__/${CONFIG_NAME}.${CONFIG_EXT} # export CONFIG_NAME=.tflint; export CONFIG_EXT=hcl
- --args=--module
```
3. Make sure that …

feat: Allow env vars expansion in `--args` section for all hooks

---

Dockerfile

Fixes #359 :
Add `alpine-sdk` package so we are able to run third party checks. This is mostly to be able to run directly this docker image with checks coming from `https://github.com/pre-commit/pre-commit-hooks` since they are widely use in combination with `pre-commit-terraform`.
This is to avoid all the users of the community using pre-commit-terraform to build their own image on top of the one existing.
FIY: This was working before the  v1.63.0. So I guess it is a change coming directly from the image of Python.
-->
1. Create a `.pre-commit-config.yaml` file containing:
```yaml
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
rev: v4.2.0
hooks:
- id: end-of-file-fixer
- id: trailing-whitespace
args: [--markdown-linebreak-ext=md]
- …
```

feat: Add support for `pre-commit/pre-commit-hooks` in Docker image

---

hooks/tfupdate.sh

Fixes #371
```yaml
repos:
rev: dfe39915d72182819814919b21b73a741ab9ae6a
hooks:
- id: tfupdate
name: Autoupdate AWS provider versions
args:
- --args=provider aws
- --args=--version 4.1.0
- id: tfupdate
name: Autoupdate Helm provider versions
args:
- --args=provider helm
- id: tfupdate
name: Update Google provider to specified version
args:
- --args=provider google
- --args=--version 4.18.0
- id: tfupdate
name: Update Terraform provider to specified version
args:
- --args=terraform
- --args=--version 1.1.8
```

fix: Fixed `tfupdate` to work in all cases, not only `pre-commit run --all`

---

.github/.container-structure-test-config.yaml
.pre-commit-hooks.yaml
Dockerfile
README.md
hooks/terraform_wrapper_module_for_each.sh

Fixes #202
To try this out, you can run it on various modules in `terraform-aws-modules` organization (e.g. https://github.com/terraform-aws-modules/terraform-aws-s3-bucket):
```yaml
- id: terraform_wrapper_module_for_each
```
Please review the shell script and suggest improvements.
The produced result should be very similar to https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/pull/270

feat: Added terraform_wrapper_module_for_each hook

---

README.md

It seems the `brew install` instructions for mac are out of date when it comes to hcledit. This fixes it. 
See: https://github.com/minamijoyo/hcledit/blob/master/README.md#homebrew

fix hcledit brew install command

---

hooks/terraform_docs.sh

The change is to the `terraform_docs` hook. Currently this hook will ignore the formatter set in any specified config file, defaulting to the `md` formatter. On our project we use the `markdown document` formatter but this is ignored by the hook. I consider this a bug but thought a PR would be better than a new issue for you.
Run:
```shellscript
$ mkdir test-tf-docs-pre-commit
$ cd test-tf-docs-pre-commit
$ git init
$ pre-commit install
```
Create the following files.
`.terraform-docs.yml`
```yaml
formatter: toml
```
`.pre-commit-config.yaml`
```yaml
repos:
- repo: https://github.com/acodeninja/pre-commit-terraform.git
rev: v1.71.0
hooks:
args:
- --args=--config=.terraform-docs.yml
```
`main.tf`
```hcl
variable "some-input" {
description = "An input variable"
type …
```

feat: When a config file is given, do not specify formatter on cli (terraform_docs)

---

hooks/terraform_fmt.sh

Fixes #379 
```yaml
repos:
rev: d0c781e98a310b1b03900280feaf630832bef332
hooks:
- id: terraform_fmt
```
Also, test details exist in https://github.com/antonbabenko/pre-commit-terraform/issues/379#issuecomment-1137194598, and the same tests was performed for this PR too.

fix: Fixed `terraform_fmt` with `tfenv`, when `terraform` default version is not specified

---

README.md

None of the above.
This PR fixes old Infracost links and mentions the behavior of the latest CLI version (which parses HCL by default).

docs: Fix Infracost links

---

README.md
hooks/terraform_checkov.sh

This PR adds support for `__GIT_WORKING_DIR__` to the new `terraform_checkov` hook.
Since the new hook cd into each directory, it now ignores the `checkov.yml` file in the root folder. The functionality can now be restored with:
```
- id: terraform_checkov
args:
- --args=--config-file __GIT_WORKING_DIR__/.checkov.yml
```
1. Create a `checkov.yml` in the top directory
2. Commit something that will trigger `terraform_checkov` in a subdirectory:
-  the config file is ignored
4. Add `--args=--config-file __GIT_WORKING_DIR__/.checkov.yml` to the `.pre-commit-config.yaml` file
5. Commit something that will trigger `terraform_checkov` in a subdirectory
- the config file is now taken into account

feat: Add __GIT_WORKING_DIR__ to terraform_checkov

---

hooks/terraform_validate.sh

That's one of many PRs to the `pre-release` branch, each one will depend on the previous one.
That is the way to include all that info in one release...
Also, close #402.

chore: Rewrite `terraform_validate` to `common::per_dir_hook`

---

README.md
hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_checkov.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terraform_wrapper_module_for_each.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

```yaml
repos:
rev: c86a8a428f59d84afb02587af3deb4bb61983351
```
```bash
PRE_COMMIT_COLOR=never pre-commit run -a
```

feat: Suppress color for all hooks if `PRE_COMMIT_COLOR=never` set

---

hooks/terraform_docs.sh

Fixes #413
`[ -e "" ]` produces result code 1 if the file is not found. And that implicitly return as result, which is not expected
```yaml
repos:
rev: 168b3aee5c9927ab104667173eb2555d381c8402
hooks:
```

fix: Fixed regression with exit code in `terraform_docs` hook

---

README.md

fix yaml syntax
it is not working with no quotes.
need to adding quotes. 

chore: Fixed yaml code snippet in README.md

---

README.md

chore: Fix `terraform_validate` exclude example

---

README.md

The `deep` CLI option has been deprecated, I've replaced it in the example.
From tflint (0.16.1):
"Failed to parse CLI options; `deep` option was removed in v0.23.0. Deep checking is now a feature of the AWS plugin, so please configure the plugin instead"

docs: Fix README tflint example

---

hooks/terraform_wrapper_module_for_each.sh

Fixes https://github.com/terraform-aws-modules/terraform-aws-acm/pull/115

fix: Fixed url for wrappers in generated README (terraform_wrapper_module_for_each)

---

.dockerignore
.github/.container-structure-test-config.yaml
.github/workflows/build-image-test.yaml
Dockerfile
README.md
hooks/terraform_wrapper_module_for_each.sh
tools/entrypoint.sh

To fix permission issues for the container running as root, the ```terraform_wrapper_module_for_each``` module is changed to add read permissions to generated ```main.tf``` files.  Also, an entrypoint wrapper script is added to create a user/group in the container that matches the desired UID and GID.
There is a "naive" version that just patches ```terraform_wrapper_module_for_each``` and updates the README documentation with a changed ```docker run``` command at https://github.com/tofupup/pre-commit-terraform/tree/4f3d2386a2d10a1a99276bd6f69f9bbe3590a15e (first 2 commits in this branch in my fork)
The entrypoint wrapper script supports su-ing to a non-root user.  It should not break existing functionality/usage of the container.  If the container is …

feat: Allow running container as non-root UID/GID for ownership issues (docker)

---

hooks/_common.sh
hooks/terraform_checkov.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

Replace for #436 ?
Close #436 #388
```
args:
- --args=--version '~> 4.2.0'
- --args=provider aws
```

feat: Add support for version constraints in `tfupdate`

---

.github/workflows/pre-commit.yaml

As per this [Github Blog post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), `set-output` and `save-state` are now considered deprecated. As of the action runner version `2.298.2`, it will begin to warn you if you use either of these commands via stdout.
This PR addresses the deprecation of `set-output` using the suggested approach in the blog post.  It should result in preventing the following warning appearing in the "Common issues check" github action [output](https://github.com/antonbabenko/pre-commit-terraform/actions/runs/3396475501/jobs/5647582776#step:4:8):
>  Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For …

chore: Fix deprecated Github Actions set-output command

---

README.md
hooks/__init__.py

fix: Describe migration instructions from `terraform_docs_replace`

---

hooks/_common.sh

Changes the escape sequence used for coloring text output to the terminal so that the colors work in zsh on MacOS.
I have tested that the output is colored correctly in zsh on MacOS and bash on MacOS.

fix: Make text color work in MacOS zsh

---

.github/workflows/pr-title.yml

Resolves deprecation warnings like the following: https://github.com/antonbabenko/pre-commit-terraform/actions/runs/3550048303

chore: Update pr-title to remove deprecation warning

---

.pre-commit-config.yaml
hooks/terraform_wrapper_module_for_each.sh

Fixed spacing in `terraform_wrapper_module_for_each` hook which was a problem when sensitive was `true` ( https://github.com/terraform-aws-modules/terraform-aws-ecs/pull/76#issuecomment-1500329275 )

fix: Fixed spacing in `terraform_wrapper_module_for_each` hook

---

.github/.container-structure-test-config.yaml
.github/.dive-ci.yaml
Dockerfile

Previous `curl` version in docker image was removed
Fixes #506
Fixes #488

fix: Updates all dependencies used in Dockerfile and fix Docker image

---

hooks/terraform_tflint.sh

Caches the output of the TFLint commands - upon failures the existing behavior was to re-run to present the output. This should speed up performance where there are lots of scattered failures in many directories.
I have tested locally with a single failing repo - showed a 48% reduction in wall clock time with the `try-repo` hooks.
Substantial speedup in a monorepo with scattered failures across many directories.

fix: Speed up x2 TFLint hook execution in dirs with violations

---

README.md

* add steps to configure netrc to source module from private GH
* fix #513
This PR adds a section to the docs to provide steps required to allow download of Terraform modules from private GitHub repositories. 
Fixes #513
1. Create a Terraform project with modules that are sources from a private GitHub repository
2. Create PAT
3. Follow steps added as part of this PR
4. Execute pre-commit on docker

docs: Add steps to configure auth to source Terraform modules from private GitHub repos

---

README.md
hooks/_common.sh
hooks/terraform_checkov.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

This change leverages the `tflint -chdir` flag to do the nested lookup and provide fully qualified paths to the output.
It unwraps the `pushd`/`popd` functionality and delegates the directory changing to the binary process via chdir.
This would be a breaking behavior if a user tried to add a `-chdir` flag to the `args` - but I can't think of a valid reason that anyone would do this - or if that functionality would even work with the pre-commit-terraform hooks.
The `-chdir` flag was added in [tflint 0.44.0](https://github.com/terraform-linters/tflint/releases/tag/v0.44.0) - I don't know how to enforce specific versions of the binary or to trivially change the commit hook driver behavior based upon the version. This flag is forwards compatible, while …

feat: TFLint: Add `--hook-config=--delegate-chdir` to use `tflint -chdir`

---

hooks/terraform_providers_lock.sh

fix: Fix `terraform_providers_lock`  hook broken in v1.79.0

---

.github/CONTRIBUTING.md
README.md

Quick improvements, which were done during work on #526, but were separated to this PR as not related changes

docs: Simplify lists maintenance and fix language

---

README.md
hooks/_common.sh
hooks/terraform_providers_lock.sh

> **Note**: Please review only after merge #527 and rebase `master` to this branch
Close #526 
```yaml
repos:
rev: 6ac6f293237ac6ad7c259a72c1112e99e7ff57b4
hooks:
- id: terraform_providers_lock
args:
- --hook-config=--mode=only-check-is-current-lockfile-cross-platform
```
```yaml
repos:
rev: 6ac6f293237ac6ad7c259a72c1112e99e7ff57b4
hooks:
- id: terraform_validate
args:
- --hook-config=--retry-once-with-cleanup=true
- id: terraform_providers_lock
args:
- --hook-config=--mode=only-check-is-current-lockfile-cross-platform
```
```yaml
repos:
rev: …
```

feat(`terraform_providers_lock`): Add `--mode` option and deprecate previous workflow

---

hooks/terraform_wrapper_module_for_each.sh

…do not have outputs or variables
The `terraform_wrapper_module_for_each` hook always exits with `1` code for modules that do not have outputs or variables defined. This is because `grep` returns an exit code of `1` when it does not find a match, and `pipefail` is set for the hook script.
This pull request resolves the issue by setting a `0` exit code for variables and outputs `grep` executions.
Run the `terraform_wrapper_module_for_each hook` against the module without outputs or variables. 🙃

fix: Fix the terraform_wrapper_module_for_each hook for modules without outputs or variables

---

hooks/terraform_wrapper_module_for_each.sh

Fixes #552 comments
If default variable values are written in heredoc style, the hook produces an error:
```
Terraform wrapper with for_each in module................................Failed
- hook id: terraform_wrapper_module_for_each
- exit code: 1
failed to build expression at the parse phase: failed to parse input: generated_by_buildExpression:21,7-7: Unterminated template string; No closing marker was found for the string.
```
This error occurs because the heredoc syntax requires the closing marker to be alone on its own line. This pull request adds a new line at the end for heredoc default values.
Also, this pull request addresses @yermulnik's comment in issue #552.
Changes can be tested against any module that has heredoc default values for …

fix: Fix terraform_wrapper_module_for_each hook heredoc vars defaults

---

.github/.container-structure-test-config.yaml
Dockerfile

- [ X ] This PR enhances existing functionality.
I have external private module in my terraform code (source="ssh://git@...."). 
In checkov we need to clone external module.
I'm using private module in git. So git need to use ssh to clone them.
I add the installation of ssh-client in the docker image.
It fixes the issue "error: cannot run ssh: No such file or directory"
From a low level point of view, start the docker image and try to clone a repository via SSH.
From a high level point of view, create a module accessible in ssh, call it from terraform,  enable terraform_checkov in pre-commit.

feat(docker): Add ssh-client to Docker image to access private modules via ssh

---

hooks/terraform_wrapper_module_for_each.sh

Modules that have `provider` blocks do not support `for_each`, `count`, or `depends_on` meta arguments. Therefore, there is no need to generate wrappers for these modules because they cannot be called.
This PR adds a skip for modules that contain a `provider` block.
Run the `terraform_wrapper_module_for_each` against the module with the `provider` block - wrapper should not be created.

feat: Skip legacy modules (with provider block) in terraform_wrapper_module_for_each hook

---

hooks/terraform_wrapper_module_for_each.sh

Put an x into the box if that apply:
I have a module with variables defined in two `.tf` files. When I run the `terraform_wrapper_module_for_each hook` locally on macOS, no changes are shown. However, when the same hooks run against the same module by GitHub Actions on Ubuntu, a difference in the order of the wrapper module input variables is shown. After researching the root cause of this behavior, I discovered that the `find` utility returns files in a different order on macOS and Ubuntu because these OS use different virtual file systems:
https://unix.stackexchange.com/questions/13451/what-is-the-directory-order-of-files-in-a-directory-used-by-ls-u
To solve this issue, I added sorting for the outputs and variables before appending them to the wrapper module.
Run the hooks against …

fix: Fixed ordering issue in terraform_wrapper_module_for_each hook

---

hooks/terraform_wrapper_module_for_each.sh

There are some providers with resources and data sources that have "variable" in their name, for example:
- [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/resources/configuration_variable)
- [env0_configuration_variable](https://registry.terraform.io/providers/env0/env0/latest/docs/data-sources/configuration_variable) data source
When using such resources, `terraform_wrapper_module_for_each` was adding these as variables to pass in `wrappers/main.tf` which breaks the wrapper 
> ╷
> │ Error: Unsupported argument
> │ 
> │   on main.tf line 14, in module "wrapper":
> │   14:   env0_configuration_variable              = try(each.value.env0_configuration_variable, var.defaults.env0_configuration_variable)
> │ …

fix: Fix terraform_wrapper_module_for_each for when resource name contains 'variable'

---

hooks/terraform_validate.sh

fix(`terraform_validate`): Run `terraform init` on "Missing required provider" error

---

.github/.container-structure-test-config.yaml
.pre-commit-hooks.yaml
Dockerfile
README.md
hooks/terraform_tfsec.sh
hooks/terraform_trivy.sh

First of all, thank you so much for your amazing work! ❤️ 
This is the first time I contribute to this repository so if there is any doubt or anything required to be fixed feel free to let me know it! 
Adds a new Trivy hook.
Fixes #550 
Create a project with a Terraform file that looks like this: 
```hcl
resource "aws_security_group_rule" "my-rule" {
type        = "ingress"
cidr_blocks = ["0.0.0.0/0"]
}
```
When running the hook it shall show two errors with this configuration and how to fix them.
In order to ignore these errors, add a comment per rule on top of the resource specifying it to ignore it:
```hcl
#trivy:ignore:AVD-AWS-0107
#trivy:ignore:AVD-AWS-0124
resource "aws_security_group_rule" "my-rule" {
type        = "ingress"
cidr_blocks = …
```

feat(trivy): Add `terraform_trivy` hook and deprecate `terraform_tfsec`

---

README.md
hooks/_common.sh

So, I found that `nproc` always shows how many CPUs available is. K8s "limits" and docker `--cpus` are throttling mechanisms, which do not hide the visibility of all cores.
There are a few workarounds, but  IMO, it is better to implement checks for that than do them
>Workaround for docker - set `--cpuset-cpus`
>Workaraund for K8s - somehow deal with [kubelet static CPU management policy](https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#cpu-management-policies), as [recommend in Reddit](https://news.ycombinator.com/item?id=25224714)
* Send all "colorify" logs through stderr, as make able to add user-facing-logs in functions that also need to return same value to function-caller

feat: Investigate and fix issue with wrong CPU count for containers

---

.pre-commit-hooks.yaml

Remove `\` before `\/` as grep 3.8 don't like it and `re.search` don't mind about it
Fix #618
These exclude patterns in pre-commit used by Python `re.search`, and it is okay with that change
https://regex101.com/
```yaml
repos:
rev: 7e213b5c4202015ee5f5ee311cd6277b5ffd0775
...
```

fix: Fix `grep: warning: stray \ before /` which pop-up in `grep 3.8`

---

hooks/_common.sh

`hooks/_common.sh`: Replace `mapfile` to support Bash v3

fix: Replace `mapfile` to support Bash 3.2.57 pre-installed in macOS 

---

.github/ISSUE_TEMPLATE/bug_report_local_install.md
Dockerfile

Follow-up release fix for
https://github.com/antonbabenko/pre-commit-terraform/pull/627

fix: Replace `mapfile` to support Bash 3.2.57 pre-installed in macOS

---

.github/workflows/build-image-test.yaml

Subset of #636 which we can easily merge now

ci(docker): Add tests for arm64

---

README.md

docs: Way we can skip directories

---

.pre-commit-hooks.yaml

When the terraform root module contains any child module it requires `terraform init` to run to be able to successfully run the provider lock operation.
Previously, `terraform init` was in `terraform_providers_lock` hook too, but moved out to be only in `terraform_validate`, because there was little sense to try to lock anything that was code invalid. 
If we return `terraform init` back to  `terraform_providers_lock` - major changes in providers that remove resources etc. can be successfully written to lockfile without any checks, as such checks done in `terraform_validate`
Add `files: (\.tf|\.tfvars|\.terraform\.lock\.hcl)$` to `terraform_validate` hook call

fix(`terraform_providers_lock`): Require `terraform init` (and `terraform_validate` hook) run when only lockfile changed

---

README.md
hooks/_common.sh

Fixes https://github.com/antonbabenko/pre-commit-terraform/issues/650
* Improve `README` by replacing sensitive `AWS_` creds vars with `AWS_PROFILE`
* Drop enclosing double quote from hook env vars
Kudos to @ericfrederich for spotting and reporting that

fix: Improve README and drop quotes from hook env vars

---

hooks/terraform_wrapper_module_for_each.sh

Rather than having `hooks/terraform_wrapper_module_for_each.sh` always create `versions.tf` for us, if the module has `versions.tf`, use that instead.
We want to do this because if your module uses a non-Hashicorp provider and `versions.tf` doesn't have a the required `required_providers` config, then Terraform will try to download the provider from Hashicorp (i.e., for the [env0 provider](https://registry.terraform.io/providers/env0/env0/latest/docs), it would try to download `hashicorp/env0` which doesn't exist and NOT `env0/env0`)... We COULD set this in the deployment code; however, if you're using Terragrunt and you configure the provider with the `required_providers` config, then if you use a root module (with proper `versions.tf`) with the …

feat: Hook terraform_wrapper_module_for_each should use versions.tf from the module if it exists

---

hooks/terraform_docs.sh

If you are using OpenTofu and don't have Terraform binary installed, terraform_docs hook will display a `command not found` error. The error line checks if Terraform release is 0.12, so it's possible suppress this error message if Terraform binary doesn't exist.
Below are the steps to reproduce the error.
1) Install OpenTofu
2) Uninstall Terraform (or remove it from PATH)
3) Make any changes to variables.tf or outputs.tf
4) Run `pre-commit -a`

fix(`terraform_docs`): Suppress "terraform command not found" error message in case binary does not exist

---

hooks/terraform_docs.sh

This PR explicitly overrides any output files configured in `.terraform-docs.yml` to ensure the rendered documentation is written to stdout (which the hook pipes to a file and then injects into the appropriate destination file).
Fixes #697
setup as per the steps to reproduce in #697 and run the hook.

fix(`terraform_docs`): Fix issue and prioritize `output.file` setting from `.terraform-docs.yml` config over `--hook-config=--path-to-file=`

---

hooks/terraform_docs.sh

fix(`terraform_docs`): Suppress redundant warnings pop-ups introduced in v1.92.2

---

README.md
hooks/terraform_docs.sh

Ensure compatibility of `terraform_docs` hook on MacOS and Linux by using GNU sed.
In PR #701, the usage of `sed` was introduced to the `terraform_docs` for in-file changes, resulting in #703
MacOS requires an extension for the `-i` parameter, unlike GNU sed.
As a result the hook fails on MacOS know with the following error:
```shell
Terraform docs..........................................................................Failed
- hook id: terraform_docs
- exit code: 1
sed: 1: "README.md": invalid command code R
```
I see two potential solutions for this issue.
1) Always pass a extension to the `-i` parameter, as this is compatible with GNU sed, too. As a result, a backup file would be created for each sed commands operation and needs to be deleted again.
2) Ensure we always use GNU sed. …

fix(`terraform_docs`): Fix non-GNU `sed` issues, introduced in v1.93.0

---

hooks/terraform_docs.sh

Relates to #705. Better merge it before #705, so they will be in same release

chore(`terraform_docs`): Change variable names, to conform to same style

---

README.md
hooks/terraform_docs.sh

Fixes #707
```yaml
repos:
rev: 70670818f5d14ba13c268dd366ecfa8374e88f42
hooks:
```

fix(`terraform_docs`): Fix non-GNU sed issues, introduced in v1.93.0, as previous fix doesn't work correctly

---

README.md

docs(`terraform_docs`): Clarify requrement of `--args=--config=`

---

hooks/_common.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_validate.sh

Add quotes around variable containing path to terraform so ti works when the path contains a space.
Fixes #713

fix: Support custom TF paths which contains spaces

---

hooks/terraform_docs.sh

Fixes #715
broken:
```
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
rev: v1.94.2 # issue introduced in 1.94.0
hooks:
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```
fixed:
```bash
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
rev: c0b1f38bae3b34f3f223bc73a8b384e2e7a766d7
hooks:
" > .pre-commit-config.yaml
git init
git add -A
pre-commit run
```
```bash
testdir=$(mktemp -d)
cd $testdir
touch main.tf README.md
echo "
repos:
rev: …
```

fix(`terraform_docs`): Restore `--hook-config=--add-to-existing-file` default behavior. Regression from 1.94.0.

---

README.md
hooks/terraform_docs.sh

Cleanup of old awk hacks introduced long time ago when `terraform-docs` wasn't able to work with terraform 0.12+.
```yaml
repos:
rev: e40ffc76df4d24fa617c46094c934847334b12c0
hooks:
args:
- "--args=--lockfile=false"
- --hook-config=--create-file-if-not-exist=true # Boolean. true or false
```

feat(`terraform_docs`): Drop support for `terraform-docs` <0.12.0

---

hooks/_common.sh

Improves https://github.com/antonbabenko/pre-commit-terraform?tab=readme-ov-file#all-hooks-usage-of-environment-variables-in---args
Found in https://github.com/antonbabenko/pre-commit-terraform/issues/718#issuecomment-2347102202
Support of [this option](https://developer.hashicorp.com/terraform/language/values/variables#environment-variables) probably will not be needed in any observed use cases, but it is cheap to implement, so here we are

feat: Expand environment variables in `--args=` which contains lowercase symbols, like `${TF_VAR_lowercase}` 

---

hooks/terraform_docs.sh

A bug in the terraform-docs hook was introduced in #717.  [In that PR, a `continue` statement was added that is not preceded by a `popd` command](https://github.com/antonbabenko/pre-commit-terraform/blob/869a106a4c8c48f34f58318a830436142e31e10a/hooks/terraform_docs.sh#L216).  The bug is only triggered when the hook is processing multiple files where one (or more) of the files does not contain the terraform-docs marker statements.  The hook fails to process the remaining files because the working directory is not reset to the root of the repository.  I ran into this bug on version 1.96.0 of the hooks and pre-commit version 3.8.0. 
Here is a script to reproduce the issue.  It creates a repository containing multiple modules.  The `pre-commit run -a` …

fix(`terraform_docs`): Fix issue with processing multiply files without `terraform-docs` markers. Issue introduced in v1.95.0

---

.pre-commit-config.yaml

Kudos to `pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks`
```shell
> pre-commit autoupdate --repo https://github.com/pre-commit/pre-commit-hooks
[https://github.com/pre-commit/pre-commit-hooks] updating v4.6.0 -> v5.0.0
> git add .pre-commit-config.yaml
> pre-commit
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
check for added large files..............................................Passed
check for merge conflicts................................................Passed
check vcs …
```

chore(deps): Update `pre-commit-hooks` version

---

hooks/_common.sh

fix(WSL): Make parallelism work appropriately

---

hooks/terraform_docs.sh

We actually faced this issue in before [here](https://github.com/antonbabenko/pre-commit-terraform/pull/620/files#diff-a9db869be8201236cd6abaed19087fc571d29c10d679fc66bf945eba1a4ccd46R297-R300), but it was eliminated before it merged to `master` branch 
Because of how our parsing works, we get these empty spaces as "beginning of key name", and  because `" foo" != "foo"`, all hook-configs except first parsed effectively ignored. This PR removes that extra space.
Fixes #721 
```yaml
repos:
rev: 819893c726df778321faf4772ae429b186887a48
hooks:
args:
- --hook-config=--add-to-existing-file=true
- --hook-config=--create-file-if-not-exist=true
```

fix(`terraform_docs`): Restore multiply `--hook-config` args support. Regression from v1.95.0

---

hatch.toml
pyproject.toml

The previously existing attempt to use `setuptools-git-version` never worked as it wasn't integrated correctly — it was added as a runtime dependency while it's meant to be a build dependency. This resulted in 0.0.0 being used all the time.
This patch adds a hatchling plugin that implements the original idea in a way that actually works.
$sbj.
`python -Im build`

chore(packaging): Fix computing SCM-based version @ the dists

---

.pre-commit-config.yaml

Enabling faster feedback loop for new contributors by enabling https://pre-commit.ci in this repo. 
The only visible effect of this is when said app is installed and the service is running the checks, it would skip the checks that rely on the external executables that might be missing in runtime. It's necessary since that testing environment is controlled by someone else.
@antonbabenko  go to https://github.com/apps/pre-commit-ci/installations/select_target, install the app into this repo and then merge the PR.

ci: Disable checks unrunable @ pre-commit.ci

---

.pre-commit-hooks.yaml
pyproject.toml
src/pre_commit_terraform/README.md
src/pre_commit_terraform/__main__.py
src/pre_commit_terraform/_cli.py
src/pre_commit_terraform/_cli_parsing.py
src/pre_commit_terraform/_cli_subcommands.py
src/pre_commit_terraform/_errors.py
src/pre_commit_terraform/_structs.py
src/pre_commit_terraform/_types.py
src/pre_commit_terraform/terraform_docs_replace.py

This includes a structure with purpose-based modules and a standard mechanism for adding more subcommands.
When adding a new subcommand, one has to define the `invoke_cli_app()` and `populate_argument_parser()` hooks in their new module together with a `CLI_SUBCOMMAND_NAME` string constant. I can then be wired into the framework via `_cli_subcommands.py`. This is the only integration point necessary.
`populate_argument_parser()` accepts a subparser instance of `argparse.ArgumentParser()` that a new subcommand would need to attach new arguments into. It does not need to return anything. And the `invoke_cli_app()` hook is called with an instance of `argparse.Namespace()` with all the arguments parsed and pre-processed. This function is supposed to have the main check logic and return an …

chore(refactoring): Introduce a Python CLI app layout

---

.github/workflows/ci-cd.yml

This turns off the "is push to master" in GitHub Actions CI/CD as it does not make sense in this environment, being local-only [[1]].
[1]: https://github.com/pre-commit/pre-commit-hooks/issues/1124
This is a follow-up for #742. One of its jobs runs `pre-commit` and doesn't filter out this hook. The hook itself would only fail on pushes to `master` which is not a condition that can happen in PR workflow runs.
You can't. This will only be visible on `master`.

ci: Disable `no-commit-to-branch` @ GHA

---

.github/.container-structure-test-config.yaml
.github/.dive-ci.yaml
.github/FUNDING.yml
.github/workflows/build-image-test.yaml
.github/workflows/build-image.yaml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yaml
.github/workflows/release.yml
.github/workflows/stale-actions.yaml
.pre-commit-config.yaml
.pre-commit-hooks.yaml
.yamllint

The initial config does not change many defaults and mostly relies on the upstream config. The only changes are to the sequence style, quoting and allowed truthy values that accomodate for GHA.
N/A
..stare at the diff? `tox r -qq -e pre-commit -- yamllint --all-files` otherwise.

chore: Integrate `yamllint` into the project

---

src/pre_commit_terraform/terraform_docs_replace.py

MyPy found that `dirs` is not annotated. This PR fix it.
coverage improved

chore(mypy): Fix type annotation

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-tox.yml
tox.ini

When you see `py` in tests it not clear what exactly going on. Until now I thought that it represents "python", but actually this part run `pytest`
So, for avoiding confusion and add ability to explicitly specify `tox r -e pytest`, this PR was made
Wait till tests pass on this PR

chore: Rename 'py' to 'pytest' in GHA to avoid confusion

---

hooks/_common.sh

Should not change anything, as it just make happy shellcheck v0.10.0 about this particular line
```bash
In hooks/_common.sh line 142:
ARGS[$arg_idx]=$arg
^------^ SC2004 (style): $/${} is unnecessary on arithmetic variables.
For more information:
https://www.shellcheck.net/wiki/SC2004 -- $/${} is unnecessary on arithmeti...
```
found in [Linters check for unrelated PR](https://github.com/antonbabenko/pre-commit-terraform/actions/runs/12758739930/job/35561336508?pr=737#step:17:46) https://github.com/antonbabenko/pre-commit-terraform/pull/737, as it uses ubutntu24.04, and no matter that `shellcheck` recommend install itself by `apt`, it contains outdated version for most OSes, IE, ubuntu22.04 uses 0.8.0, when latest one is 0.10.0
Actually, we can do it as PATCH release, but I am not sure is …

chore: Fix shellcheck v0.10.0 linters rules

---

.github/renovate.json5

We are hit limits for how many runs on MacOS runners can be run, just by creation 10 renovate PRs and fix twise issues in half of them ~= 20 new PRs/commits for check
Each commit trigger 10 MacOS runs, which means that limit is aproximatly ~200 MacOS runs per hour.
I didn't find such limits in offical docs, btw
https://docs.github.com/en/actions/administering-github-actions/usage-limits-billing-and-administration#usage-limits

ci: Avoid reaching GH limits on MacOS runners

---

.git_archival.txt
.gitattributes
hatch.toml

It's a follow-up to #735 that lacks this property. It's also an internal change.
It essentially allows one to
```
$ pip install https://github.com/antonbabenko/pre-commit-terraform/archive/a7155a7.tar.gz
```
and get a correctly computed version in the installed metadata.
[1]: https://setuptools-scm.rtfd.io/en/latest/usage/#git-archives
See above.
```
$ pip install https://github.com/antonbabenko/pre-commit-terraform/archive/a7155a7.tar.gz
```

chore(packaging): Enable support for versioning Git archives

---

.github/CONTRIBUTING.md
.github/workflows/reusable-tox.yml
pytest.ini
tox.ini

* Add notes for contributors
* Describe what different parts of code does, for simplifying future maintenance if it will be needed

docs: Simplify undestanding what's going on

---

README.md
hooks/terraform_docs.sh

This adds support to pass custom markers.
This helps to improve support for other formats like asciidoc which you can use if you use a config for terraform-doc.
Add your custom marker to a README and run the hook with the options. You may also want to change the template used by terraform-doc
```
terraform_docs.sh --hook-config=--path-to-file=README.adoc --hook-config="--custom-marker-begin=// BEGIN_TF_DOCS" --hook-config="--custom-marker-end=// END_TF_DOCS" --args=--config=.terraform-docs.yml ./path/to/file.tf
```

feat(`terraform_docs`): Add support for custom markers to better support other formats than Markdown

---

.github/workflows/ci-cd.yml

Each failed nightly build occurs right when new tag released and tag point to latest commit.
To avoid that, we need to drop tag to HEAD in CI
1. Fork repo with all branches
2. Create PR from this branch and merge to fork `master`
3. Manually make new release
4. Go to Actions -> Enable :hourglass:  action
5. Trigger :hourglass: action manually
https://github.com/MaxymVlasov/pre-commit-terraform-PR776/actions/runs/12916272093

ci: Fix edge case with Nightly builds right after new release

---

.github/workflows/dependency-review.yml

Changes in this pull request is provided by [StepSecurity](https://app.stepsecurity.io/securerepo) 
The Dependency Review Workflow enforces dependency reviews on your pull requests. The action scans for vulnerable versions of dependencies introduced by package version changes in pull requests, and warns you about the associated security vulnerabilities. This gives you better visibility of what's changing in a pull request, and helps prevent vulnerabilities being added to your repository.
- [Github Guide about Dependency Review](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review)
- [Github Guide for Configuring Dependency Review Action](https://docs.github.com/en/code-security/supply-chain-security/understanding-yo …

ci(StepSecurity): Add Dependency Review Workflow

---

.github/workflows/ci-cd.yml
.github/workflows/reusable-tox.yml

Changes in this pull request is provided by [StepSecurity](https://app.stepsecurity.io/securerepo) 
GitHub Action tags and Docker tags are mutable. This poses a security risk. GitHub's Security Hardening guide recommends pinning actions to full length commit.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies)

chore(StepSecurity): Pin dependecies

---

.pre-commit-config.yaml

Changes in this pull request is provided by [StepSecurity](https://app.stepsecurity.io/securerepo) 
Pre-commit is a framework for managing and maintaining multi-language pre-commit hooks. Hooks can be any scripts, code, or binaries that run at any stage of the git workflow. Pre-commit hooks are useful for enforcing code quality, code formatting, and detecting security vulnerabilities.
- [Official Pre-commit documentation](https://pre-commit.com/)
- [Getting Started guide](https://pre-commit.com/#getting-started)
---
> [!NOTE]
> At least now we know what about this repo is :D

chore(StepSecurity): Add `gitleaks` pre-commit hook; rearange hooks

---

.github/workflows/build-image-test.yaml
.github/workflows/build-image.yaml

Deal with
```
ERROR: invalid tag "ghcr.io/MaxymVlasov/pre-commit-terraform-712:latest": repository name must be lowercase
```
Found during testing changes for #712 - as I need to test all workflows without disrupting main repo

ci: Make able to run workflow in forks with uppercase in names

---

.github/workflows/build-image-test.yaml
.github/workflows/build-image.yaml
.github/workflows/ci-cd.yml
.github/workflows/pr-title.yml
.github/workflows/pre-commit.yaml
.github/workflows/release.yml
.github/workflows/reusable-tox.yml
.github/workflows/scheduled-runs.yml
.github/workflows/stale-actions.yaml

Changes in this pull request is provided by [StepSecurity](https://app.stepsecurity.io/securerepo) 
The GITHUB_TOKEN is an automatically generated secret to make authenticated calls to the GitHub API. GitHub recommends setting minimum token permissions for the GITHUB_TOKEN.
- [GitHub Security Guide](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
- [The Open Source Security Foundation (OpenSSF) Security Guide](https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions)
Relates: #712

ci(StepSecurity): Harden GHA token permissions 

---

.github/workflows/build-image-test.yaml
.github/workflows/build-image.yaml

This should speed up docker image build process during tests and wipe out one of dependencies

ci: Utilize native arm64 linux runners

---

.coderabbit.yaml

Except what was already here, I changed next settings:
* Disable: related_issues, related_prs - to not make useless cross-links between PRs and issues
* Collapse Walkthrough - as it took too much place in PR and needed just for first interaction.
* Move summary to Walkthrough
<details>
<summary>current CodeRabbit configuration</summary>
```yaml
language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
profile: chill
request_changes_workflow: false
high_level_summary: true
high_level_summary_placeholder: '@coderabbitai summary'
high_level_summary_in_walkthrough: false
auto_title_placeholder: '@coderabbitai'
auto_title_instructions: ''
review_status: true
commit_status: true
fail_commit_status: false
collapse_walkthrough: false
changed_files_summary: true …
```

chore(coderabbitai): Codify and improve config

---

README.md

Relates #785 
Met next requirement:
> The project website MUST succinctly describe what the software does (what problem does it solve?). [description_good]
This MUST be in language that potential users can understand (e.g., it uses minimal jargon).

docs: Describe succinctly what the software does (what problem does it solve?)

---

.codecov.yml
.github/workflows/ci-cd.yml
.github/workflows/reusable-tox.yml
.github/workflows/stale-actions.yaml
.pre-commit-config.yaml
.yamllint

`yamlfmt` does not support inline comments in `key: >-  # comment` construction - it removes such comments.
That's only one incontinence which I see for that linter, so it's good enough to force its use

chore(linters): Add yamlfmt

---

README.md

For now, remove Terramate from sponsors.

docs: Remove terramate from sponsors

---

.github/workflows/ci-cd.yml
Dockerfile

Relates #712 
Based on https://github.com/ossf/scorecard/issues/3684#issuecomment-2683942964
I am not sure that pining python deps to major version will make any difference for OSSF, but at least we will specify what major versions we currently rely on

fix(docker image security): Improve dependency pinning and disable ability to build image from different than specified in dockefile tag

---

.github/workflows/reusable-tox.yml

Workaround for https://github.com/codecov/codecov-action/issues/1794
Close https://github.com/antonbabenko/pre-commit-terraform/pull/843

chore(codecov): Ignore errors during codecov upload

---

Dockerfile

- [ x] This PR fixes a bug.
Before
```
$ podman run --rm --entrypoint cat ghcr.io/antonbabenko/pre-commit-terraform:latest less /usr/bin/tools_versions_info
pre-commit 4.1.0
./tofu --version | head -n 1
./terraform --version | head -n 1
checkov 3.2.377
hcledit 0.2.17
Infracost v0.10.40
terraform-docs version v0.19.0 af31cc6 linux/amd64
terragrunt version v0.73.14
terrascan version: v1.19.9
TFLint version 0.55.1
+ ruleset.terraform (0.10.0-bundled)
tfsec v1.28.13
tfupdate 0.8.5
trivy Version: 0.59.1
```
After
```
pre-commit 4.1.0
tofu OpenTofu v1.9.0
terraform (./terraform --version | head -n 1)
checkov 3.2.386
hcledit 0.2.17
Infracost v0.10.41
terraform-docs version v0.19.0 af31cc6 linux/amd64
terragrunt version v0.75.10
terrascan version: v1.19.9 …
```

chore(docker debug): Display opentofu & terraform versions

---

.github/workflows/build-image-test.yaml
README.md

* Point `changed-files` step to correct scripts dir
* sort file alphabeticaly
* Describe current state of docker security
Relates to #835 (this PR should trigger a one-off Docker image rebuild to bring it up-to-date as requested in linked issue)
@MaxymVlasov Maybe it might make sense to schedule Docker image rebuild every other week, biweekly, or so?

docs(docker): Describe current state of docker image security plus minor fixes

---

.hadolint.yaml
.pre-commit-config.yaml
Dockerfile
tests/Dockerfile

Split from https://github.com/antonbabenko/pre-commit-terraform/pull/831
Hadolint supports its own config file, and that make able 3rd-party tools that utilize hadolint also known about specified config options, not pre-commit only

chore(linters): Reorder linters, make hadolint ignores more specific

---

tools/entrypoint.sh

Get `wdirgitindex` from $(git rev-parse --git-dir) to make it correct for non-worktree repos, and for worktree repos in either the main worktree or linked worktree.
Fixes #844 
1. Reproduce the error as per the issue #844 
2. build a new docker image using this PR's change to `entrypoint.sh`
3. run the docker image:
- without any worktree (use `git worktree remove $br` if you already created one in the repro steps), using the usual docker run command (not the repro one)
- with a worktree, but from the main repo path, using the usual docker run command (not the repro one)
- with a worktree, from the worktree path (use the repro steps in the issue to edit the .git file, and mount the /gitcommon mount)

feat(docker): Support execution on repos under `git worktree`

---

src/pre_commit_terraform/_cli_parsing.py
src/pre_commit_terraform/_errors.py
src/pre_commit_terraform/_types.py
src/pre_commit_terraform/terraform_docs_replace.py
tests/pytest/_cli_test.py
tests/pytest/terraform_docs_replace_test.py

Subset of https://github.com/antonbabenko/pre-commit-terraform/pull/831
Result of run
```yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
rev: v0.8.4
hooks:
- id: ruff-format
```
with same `ruff.toml` as in #831, exept 2 last lines which enable ignore of deprecated hooks (https://github.com/antonbabenko/pre-commit-terraform/blob/948a36d52d36270c329028bd27f7a3e999c899ff/ruff.toml)

chore(linters): Apply ruff-format

---

.git-blame-ignore-revs
.github/CONTRIBUTING.md

Follow-up to https://github.com/antonbabenko/pre-commit-terraform/pull/861

chore: Ignore ruff-format apply in git blame

---

src/pre_commit_terraform/__main__.py
src/pre_commit_terraform/_cli.py
src/pre_commit_terraform/_cli_parsing.py
src/pre_commit_terraform/terraform_docs_replace.py
tests/pytest/_cli_test.py
tests/pytest/terraform_docs_replace_test.py

Subset of #831 
Apply next for each violation:
```yaml
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
rev: v0.8.4
hooks:
- id: ruff
args:
- --fix
- --unsafe-fixes
- --select=<rulename>
- id: ruff-format
```
and commit as separate commit
with same `ruff.toml` as in #831, except 2 last lines which enable ignore of deprecated hooks (https://github.com/antonbabenko/pre-commit-terraform/blob/948a36d52d36270c329028bd27f7a3e999c899ff/ruff.toml)

chore(linters): Apply ruff linter semi-automatic linting fixes

---

src/pre_commit_terraform/_cli.py
src/pre_commit_terraform/_errors.py
src/pre_commit_terraform/terraform_docs_replace.py
tests/pytest/terraform_docs_replace_test.py

Subset of https://github.com/antonbabenko/pre-commit-terraform/pull/831/

chore(liners): Suppress ruff rules which shouldn't be fixed

---

hooks/_common.sh

Add a version of `WSLInterop` file that exists in WSL with SystemD enabled.
Ref: https://github.com/Mozilla-Ocho/llamafile/issues/275
Fixes #871 
Or should we better use something like `grep -qi Microsoft /proc/version` (ref: https://github.com/microsoft/WSL/issues/4071) — @MaxymVlasov What do you think? 🤔

fix(WSL): Fix parallelism support for WSL systems with enabled systemd

---

.pre-commit-hooks.yaml

Opentofu added `.tofu` extension a some time ago for not supported by vanilla Terraform syntax.
https://github.com/terraform-docs/terraform-docs/releases/tag/v0.20.0 also added support for `.tofu`.
All other hooks should be fine with `.tofu` too.

feat: Add support for running hooks on `.tofu` files by default

---

.github/workflows/pre-commit.yaml

Deal with 
> Error: getCacheEntry failed: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP. For more information: https://gh.io/gha-cache-sunset
https://github.com/antonbabenko/pre-commit-terraform/actions/runs/14755939444/job/41424052063?pr=589
@antonbabenko please,
1. run `ssh-keygen -t ed25519` locally
2. Add private key as  repo secret with name exactly  `GHA_AUTOFIX_COMMIT_KEY` at https://github.com/antonbabenko/pre-commit-terraform/settings/secrets/actions
3. Add public key as Deploy key with name like `GHA_AUTOFIX` at https://github.com/antonbabenko/pre-commit-terraform/settings/keys
And then we will be able to test it this PR

chore(ci): Fix `pre-commit/action`, as v2.x not work anymore

---

.github/workflows/pre-commit.yaml

Follow-up to https://github.com/antonbabenko/pre-commit-terraform/pull/878
It also fixes `Error: A branch or tag with the name 'add-graph-hook' could not be found` for forks
https://github.com/antonbabenko/pre-commit-terraform/actions/runs/14795718154/job/41542245011?pr=589

chore(ci): Remove duplication checkout

---

README.md

`--module` was deprecated in TFLint v0.50.0 and removed in v0.54.0.
According to https://github.com/antonbabenko/pre-commit-terraform/issues/534#issuecomment-2858451826, it should be replaced to `--call-module-type="all"`

docs(tflint): Replace deprecated value in example

---

README.md

* Previously, these docs wrongly assumed that repo was `git init`/`git clone` after setting up of `init.templateDir`, which is not the case for 90%+ of newcomers.
* Installation instructions were too far away for list of dependencies, so it were easy to interpret that you need to install all these deps manually, and only then find out that there are already instructions that cover their installation. Rearranging them slightly, fix that issues

docs: Add missed step for init'ed repos and resolve confusion that deps should be find out and installed manually

---

.github/workflows/build-image-test.yaml
.github/workflows/codeql.yml
.github/workflows/dependency-review.yml
.github/workflows/pre-commit.yaml

I previously tried to automate Renovate PR merges, but it works poorly, plus it's time to time violate review process.
So, to address known issues with time-consuming merge of many Renovate PRs at once, make OpenSSF scorecard happier in terms of branch protection rules (https://github.com/antonbabenko/pre-commit-terraform/issues/712) and make finally get ability to merge many Renovate PRs at once - let's enable Merge queue for PRs.
For this, required:
1. Merge this PR
2. Change branch protection ruleset slightly (will send instructions to Anton later)
3. Enable Merge Queue in repo settings.   
UPD. Merge Queue is accessible only for organizations... So we're can't use it right now, but I'll merge it anyway in case if we will migrate to organization one day

chore(ci): Prepare to switch to Merge Queue for PR merging

---

.github/renovate.json5
.pre-commit-config.yaml

Pinned by `pre-commit autoupdate --freeze` as `pre-commit` in Renovate currently [does not support](https://github.com/renovatebot/renovate/discussions/22488) freezing style used by `pre-commit`

chore(security): Pin pre-commit hooks by SHA, as it is immutable

---

hooks/infracost_breakdown.sh

pull-back from fork
This fixes the error `line 77: -1: substring expression < 0` and replaces mapfile with something compatible for bash 3.x
-    Replace mapfile with while-read loop for bash 3.2 compatibility
-    Fix substring expressions to avoid negative indices: (${check: -1} => ${check:$((${#check}-1)):1})
-    Replace negative array indexing with explicit length calculation
-    Maintain identical functionality while supporting macOS default bash version
I only tested my own use case which is to get a failed check if `.totalMonthlyCost` crosses a threshold:
```yaml
hooks:
- id: infracost_breakdown
args:
- --args=--path=./
- --hook-config='.totalMonthlyCost|tonumber < 4'
- --hook-config='.currency == "USD"'
```

fix(`infracost_breakdown`): Make hook compatible with bash 3.2 (macOS)

---

hooks/terraform_docs.sh
hooks/terraform_wrapper_module_for_each.sh

Pull-back from fork
There are a few places inside hooks where search by extension performed, and previously it missed check for `.tofu`

fix(`terraform_docs`, `terraform_wrapper_module_for_each`): Improve `.tofu` files support

---

tools/install/checkov.sh
tools/install/pre-commit.sh

Check `pip` after each installation, to ensure that everything still works correctl
Address https://github.com/antonbabenko/pre-commit-terraform/pull/635#discussion_r1521227039:
> *do not* install distributions with pip separately because it will not take all things installed in the previous session into account when you run a new install command. Enumerate everything and let the dependency resolver know all your requirements together. Ideally, use pip-compile to produce and commit constraint files (lockfiles) and invoke it via `pip install -r direct-deps.txt -c constraint.txt`.
> If you do run separate pip installs, inject a `pip check` invocation at the end to verify integrity.
I suppose it should be runs just once at the end of installation, but it's mostly free to run `pip check` …

chore(docker): Add integrity validation for separately installed pip packages

---

tools/install/checkov.sh

Drop not more needed to hack for `checkov` during docker images installation, as https://github.com/bridgecrewio/checkov/pull/7072 merged 3 months ago as `3.2.395`.
That's make obsolete hack from https://github.com/antonbabenko/pre-commit-terraform/pull/635 as https://github.com/bridgecrewio/checkov/pull/7072 finally closes https://github.com/bridgecrewio/checkov/issues/5608 for Mac arm64, because `checkov` finally uses `rustworkx >= 0.14.0`

fix(docker): Drop Mac arm64 build-time hack, needed for `checkov`<3.2.395

---

README.md

docs: Clarify docker instructions to work with spaces in paths

---

.github/.container-structure-test-config.yaml
Dockerfile
tools/install/checkov.sh

In https://github.com/antonbabenko/pre-commit-terraform/pull/915 I find out that current base docker image wasn't updated for 6 months, as Renovate updates SHA, but for some reason doesn't update image tag version (not supported?).
To fix that, I loose tag, to get latest security updates for docker image

chore(deps): Use latest available Python 3.12 base image

---

.pre-commit-hooks.yaml

This adds `.tftest.hcl` and `.tfmock.hcl` to the default `files` attribute for the `terraform_fmt` hook config.
Support for formatting these files were added in recent terraform versions
---
Notes by @MaxymVlasov:
* `terraform fmt` definitely supports `.tfmock.hcl` , because not supporting of it was reported as a bug, and now is resolved by addition of such support - https://github.com/hashicorp/terraform/issues/34577 
* And `.tftest.hcl` also mentioned in `fmtSupportedExts` - https://github.com/hashicorp/terraform/blob/0c63fb2b097edcd5cb1a91322765a414206fbea2/internal/command/fmt.go#L30-L35

feat(`terraform_fmt`): Add support for `.tftest.hcl` and `.tfmock.hcl` formatting

---

hooks/terragrunt_providers_lock.sh
hooks/terragrunt_validate.sh

Terragrunt's `run`/`run-all` command requires a `--` before commands that get passed to Terraform to proper handle passed arguments. Without the `--` any arguments passed via `args: [--arg=-foo]` would get interpreted as Terragrunt argument rather than a Terraform argument. 
The currently used way without `--` is just a shortcut:
```
❯ terragrunt run --help
Usage: terragrunt run [options] -- <tofu/terraform command>
...
Examples:
terragrunt run -- plan
```
Try e.g. this configuration:
```yaml
repos:
hooks:
- id: terragrunt_providers_lock
args:
- --args=-platform=linux_amd64
- --args=-platform=darwin_arm64
```
Without this PR, the above would fail with:
```
Terragrunt providers …
```

fix(terragrunt_providers_lock, terragrunt_validate): Proper argument handling
