antonbabenko/pre-commit-terraform

hooks.yaml

Exclude .terraform even on subfolders

---

terraform_validate_no_variables.sh
terraform_validate_with_variables.sh

Only run validate if .tf files exist in the directory.

---

README.md

Added the top-level repos map that was introduced in pre-commit 1.0.0.

docs: Fixed the docs to use the latest config syntax

---

.pre-commit-hooks.yaml
README.md

feat: Add checkov support

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml

fix: Terraform validate for submodules

---

README.md

updates readme regarding install of
- macOS
- ubuntu

docs: Updated README regarding installation steps

---

README.md

Need for ```sudo``` to move executable to ```/usr/bin```

Update Ubuntu install method

---

.github/ISSUE_TEMPLATE/bug_report_docker.md
.github/ISSUE_TEMPLATE/bug_report_local_install--.md
.github/ISSUE_TEMPLATE/bug_report_local_install.md
.github/ISSUE_TEMPLATE/feature_request.md

Fix label auto-adding after label rename
Create new issues from each template

fix: label auto-adding after label rename

---

terraform_docs.sh

`terraform-docs` does not care about tfvars, the variable is unused inside the script
and probably was originally copy-pasted from another hook.
Tested locally against a client project.

fix: remove dead code from terraform-docs script

---

.github/workflows/pre-commit.yaml

Fixes #230
During workflow run. Battle-tested in other repo.

chore: Add shfmt to workflow

---

Dockerfile

If INSTALL_ALL is not set, the docker image won't build. 
docker build

fix: Dockerfile if INSTALL_ALL is not defined

---

README.md

Preview: https://github.com/antonbabenko/pre-commit-terraform/tree/docs/contributors#authors

docs: Make contributors more visible

---

.github/workflows/pre-commit.yaml

Details:
https://github.com/actions/checkout/issues/27#issuecomment-889317591

chore: Fix master merge to working branch on pre-commit autofixes

---

.pre-commit-hooks.yaml

fix: Properly exclude .terraform directory with checkov hook

---

.github/workflows/release.yml

chore: Release action should track hooks configuration changes

---

.github/PULL_REQUEST_TEMPLATE.md

Last time new contributors provide useless info about testing. Let's make PR description more strict.

chore: Specify what we exactly mean

---

.github/workflows/build-image-test.yaml

Closes #291 
Still need to add smoke tests.
On my local branch.

chore: Add Github Actions Workflow to build if Dockerfile updated

---

.pre-commit-hooks.yaml

Bug not yet released, so it fix not needed release too.

fix: Fix bug introduced in #316

---

.github/workflows/build-image.yaml

Add Docker image latest and nightly tag according to https://github.com/antonbabenko/pre-commit-terraform/issues/321
github docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onschedule
- tested release on my forked repo
- tested nightly build on my forked repo

chore: Add Docker latest and nightly tag

---

README.md

- [x ] This PR fixes a bug.
fixes: #344

docs: Fix README function `rm_terraform` to not erase .terraform-docs.yaml

---

README.md

[![RussianWarship](https://raw.githubusercontent.com/vshymanskyy/StandWithUkraine/main/badges/RussianWarship.svg)](https://github.com/vshymanskyy/StandWithUkraine/blob/main/docs/README.md)

feat: Add important notes about project

---

.pre-commit-config.yaml

chore: Fix linter

---

README.md

docs: Document `--terraform-plan-flags` usage limitations for infracost

---

.github/.container-structure-test-config.yaml
.github/.dive-ci.yaml
.github/CONTRIBUTING.md
.github/workflows/build-image-test.yaml

Close #325
By GH Action `build-image-test.yaml`

chore: Add docker image tests - `container-structure-test-config` and `dive-ci`

---

.github/.container-structure-test-config.yaml
Dockerfile

Fixes #370
```bash
git checkout fix/GH-370/fix_docker
docker build -t pre-commit-terraform --build-arg INSTALL_ALL=true .
cd TEST_REPO
docker run -v $(pwd):/lint -it  -w /lint pre-commit-terraform:latest run -a
```

fix: Fixed git fatal error in Dockerfile

---

README.md

chore: Clarify `terraform-docs` config usage

---

README.md

Infracost 0.10 has some changes in the names of the flags.
Ref: https://twitter.com/AliKhajeh/status/1530081914865868802

docs: Updated docs for infracost_breakdown to match Infracost 0.10

---

README.md
hooks/_common.sh
hooks/terraform_providers_lock.sh
hooks/terraform_validate.sh

fix: Add `--tf-init-args`, deprecate `--init-args`

---

README.md
hooks/_common.sh
hooks/infracost_breakdown.sh
hooks/terraform_checkov.sh
hooks/terraform_docs.sh
hooks/terraform_fmt.sh
hooks/terraform_providers_lock.sh
hooks/terraform_tflint.sh
hooks/terraform_tfsec.sh
hooks/terraform_validate.sh
hooks/terraform_wrapper_module_for_each.sh
hooks/terragrunt_fmt.sh
hooks/terragrunt_validate.sh
hooks/terrascan.sh
hooks/tfupdate.sh

@antonbabenko as you requested.
DO NOT SQUASH THIS PR

feat: Preparing variables for upcoming renaming (next major release) + features

---

README.md

chore: Add more obvious dependencies into README

---

.github/workflows/pre-commit.yaml

chore: Fix pre-commit workflow

---

.pre-commit-hooks.yaml

Fixes #569
```yaml
repos:
rev: 3fff91fc5c4237be669f9f1e2bfac1c3f089ac8d
hooks:
- id: terraform_tfsec
```

fix: Run `terraform_tfsec` only on terraform code changes

---

README.md

It just looks nice
Preview: https://github.com/antonbabenko/pre-commit-terraform/tree/ceead59dc3833686059dc03b29d2ee26e29a44e1#authors

chore: Add star history to README

---

.github/workflows/stale-actions.yaml

chore: Fix conflict with Renovate issue

---

.github/ISSUE_TEMPLATE/bug_report_local_install.md
Dockerfile
README.md

Implementing https://github.com/orgs/community/discussions/16925

docs: Revisit docs constructuons to Github markdown extension

---

.github/workflows/build-image-test.yaml

https://github.com/antonbabenko/pre-commit-terraform/security/dependabot/1

chore(deps): Update tj-actions/changed-files to fix dependabot alert

---

README.md

docs: Document that `__GIT_WORKING_DIR__` available for `terraform_trivy`

---

.github/ISSUE_TEMPLATE/bug_report_docker.md
.github/ISSUE_TEMPLATE/bug_report_local_install.md

chore: Fix YAML highlighting in issue templates

chore: Fix YAML highlighting in issue templates

---

README.md

docs: Fix typo and check all development flow

---

README.md

small typo in the link for the workflow yaml file (`yml` -> `yaml`).
Fixes the link for the [pre-commit-terraform github workflow yaml file](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.github/workflows/pre-commit.yaml).
Click the link!

docs: Fix broken github actions link

---

pyproject.toml

Please let me know if you want your emails here - they already specified in your GH profiles, so...
Addressing https://github.com/antonbabenko/pre-commit-terraform/pull/733#pullrequestreview-2524482423

chore: Set right values in pyproject.toml form authors and maintainers

---

.github/renovate.json5

Just want to see green checks for Renovate PRs, as now hard to understand current status till you check PR

chore(renovate): Require first upper letter in PR titles

---

.github/SECURITY.md

chore: Add SECURITY policy that conforms with OSSF requirements
